// =============================================================================
// src/core/types.ts - Core Interface & Type Definitions
// =============================================================================
//
// [Design Principles]
//
// This file corresponds to the "Domain Layer" in clean architecture.
// It has zero external dependencies and defines the core contracts of the system.
//
// All layers (core, adapters, app) depend on these interfaces,
// but this file itself depends on nothing. (Dependency Inversion Principle)
//
// =============================================================================

// =============================================================================
// Channel Event
// =============================================================================
//
// The basic unit of events delivered to Claude Code sessions via channels.
//
// - content: The event body that Claude actually reads and analyzes
//   → Becomes the inner text of the <channel> tag
//
// - meta: Metadata converted to <channel> tag attributes
//   → Used for routing, identification, filtering, etc.
//   → Keys must be alphanumeric/underscores only (no hyphens!)
//   → Example: { request_id: "1", method: "POST", path: "/test" }
//
// Result example:
//   <channel source="my-channel" request_id="1" method="POST" path="/test">
//     Event body content...
//   </channel>
//
// =============================================================================
export interface ChannelEvent {
  content: string
  meta?: Record<string, string>
}

// =============================================================================
// Event Emit Function Type
// =============================================================================
//
// Function type used by adapters to deliver events to the bridge.
//
// [Strategy Pattern Applied]
// By injecting this function into IEventSource.start(),
// adapters don't need to know "where events are sent."
// They just call the emit function provided by the bridge.
//
// This allows replacing the bridge implementation
// without changing adapter code.
//
// =============================================================================
export type EventEmitFn = (event: ChannelEvent) => Promise<void>

// =============================================================================
// Event Source Interface (IEventSource)
// =============================================================================
//
// [Strategy Pattern]
// Abstracts various event sources (HTTP, scheduler, WebSocket, etc.)
// behind a unified interface.
// Since ChannelBridge depends only on this interface,
// adding new event sources doesn't require modifying bridge code.
//
// Implementation examples:
//   - HttpAdapter: Converts HTTP requests to events
//   - SchedulerAdapter: Converts periodic job results to events
//   - TelegramAdapter: Converts Telegram messages to events (custom)
//
// =============================================================================
export interface IEventSource {
  // Unique name of the event source (for logging/debugging)
  readonly name: string

  // Start the event source
  // emit: function to call when an event occurs (injected by bridge)
  start(emit: EventEmitFn): Promise<void>

  // Stop the event source (Graceful Shutdown)
  stop(): Promise<void>
}

// =============================================================================
// Reply Handler Interface (IReplyHandler)
// =============================================================================
//
// Handles processing when Claude calls the reply tool.
//
// [Dependency Inversion Principle (DIP)]
// The core layer (channel-bridge) depends only on this interface.
// Actual implementation (SSE, Telegram, etc.) is decided in the app layer.
//
// Implementation examples:
//   - Send via SSE stream (built-in)
//   - Send as Telegram message (custom)
//   - Send as Slack message (custom)
//
// =============================================================================
export interface IReplyHandler {
  // Called when Claude invokes the reply tool
  // requestId: identifies which request this is a response to
  // text: response text generated by Claude
  onReply(requestId: string, text: string): Promise<void>
}

// =============================================================================
// Permission Request Info
// =============================================================================
//
// Information delivered when Claude needs user approval
// to use tools like Bash, Write, etc.
//
// By receiving this info and forwarding it remotely (chat app, SSE stream, etc.),
// approval/denial can be handled without terminal access.
//
// =============================================================================
export interface PermissionRequest {
  // 5-char lowercase ID (excluding 'l' to avoid confusion with 1/I)
  requestId: string
  // Name of the tool requiring approval (e.g., "Bash", "Write")
  toolName: string
  // Description of the operation the tool will perform
  description: string
  // Preview of tool arguments (max 200 chars)
  inputPreview: string
}

// =============================================================================
// Permission Handler Interface (IPermissionHandler)
// =============================================================================
//
// Handles Claude's tool usage permission requests and results.
//
// Flow:
//   1. Claude requests tool usage
//      → onPermissionRequest() called (forward approval request remotely)
//   2. User approves/denies remotely
//      → Signal delivered via HTTP /permission endpoint, etc.
//   3. onPermissionVerdict() called → Result forwarded to Claude Code
//
// =============================================================================
export interface IPermissionHandler {
  // Called when a permission request arrives from Claude Code
  onPermissionRequest(req: PermissionRequest): Promise<void>
  // Called when the user makes an approval/denial decision
  // allow: true for approve, false for deny
  onPermissionVerdict(requestId: string, allow: boolean): Promise<void>
}

// =============================================================================
// Channel Bridge Config
// =============================================================================
//
// Configuration values needed for MCP server creation.
//
// Instructions are added to Claude's system prompt, so
// clearly describe "what events arrive" and "how to respond."
// The quality of these instructions determines Claude's response quality.
//
// =============================================================================
export interface ChannelBridgeConfig {
  // MCP server name (channel name displayed in Claude Code)
  name: string
  // Version string (e.g., "0.0.1")
  version: string
  // Instructions delivered to Claude (added to system prompt)
  instructions: string
  // Enable permission relay feature (default: false)
  // true: When Claude requests tool approval, forward to IPermissionHandler
  enablePermissionRelay?: boolean
  // Enable reply tool (default: false)
  // true: Claude can respond using reply tool (bidirectional communication)
  enableReplyTool?: boolean
}
